language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 7.4
          env:
              - COMPOSER_UPDATE_FLAGS=--ignore-platform-reqs
        - php: nightly
          env:
              - COMPOSER_UPDATE_FLAGS=--ignore-platform-reqs
              - PHP_CS_FIXER_IGNORE_ENV=true

before_install:
    - travis_retry composer self-update --no-interaction

install:
    - travis_retry composer update --no-interaction --prefer-dist --optimize-autoloader ${COMPOSER_UPDATE_FLAGS}

script:
    - composer ci-run